name: 'cicd'
on: 
  workflow_call:
    # inputs:
    #   param1:
    #     type: number
    #     description: Param 1
    #     required: true 
    #   param2:
    #     description: Param 2
    #     required: true 
    #     type: number  
jobs: 
  using-docker:
    runs-on: ubuntu-22.04 
    steps:
      - name: Do calculation 
        id: script 
        uses: docker://jeanlucsemedo/script:1.0 
        with:
          args: 
            1
            3
      - name: Output results 
        run: echo "This is the result ${{steps.script.outputs.result}}"

      
